In [41]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [42]:
df=pd.read_csv("clen_bike.csv")

In [43]:
df.head()

   Unnamed: 0  owner          brand     price  kms_driven  age  power
0           0      1            TVS   35000.0     17654.0  3.0  110.0
1           1      1  Royal Enfield  119900.0     11000.0  4.0  350.0
2           2      1        Triumph  600000.0       110.0  8.0  675.0
3           3      1            TVS   65000.0     16329.0  4.0  180.0
4           4      1         Yamaha   80000.0     10000.0  3.0  150.0

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7306 entries, 0 to 7305
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  7306 non-null   int64
 1   owner       7306 non-null   int64
 2   brand       7306 non-null   object
 3   price       7306 non-null   float64
 4   kms_driven  7306 non-null   float64
 5   age         7306 non-null   float64
 6   power       7306 non-null   float64
dtypes: float64(4), int64(2), object(1)
memory usage: 399.7+ KB

In [45]:
df['brand'].unique()

array(['TVS', 'Royal Enfield', 'Triumph', 'Yamaha', 'Honda', 'Hero',
       'Bajaj', 'Suzuki', 'Benelli', 'KTM', 'Mahindra', 'Kawasaki',
       'Ducati', 'Hyosung', 'Harley-Davidson', 'Jawa', 'BMW', 'Indian',
       'Rajdoot', 'LML', 'Yezdi', 'MV', 'Ideal'], dtype=object)

In [46]:
char=df.select_dtypes(include='object')
num=df.select_dtypes(exclude='object')

In [47]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
7301    False
7302    False
7303    False
7304    False
7305    False
Length: 7306, dtype: bool

In [48]:
df.drop_duplicates(inplace=True)

In [49]:
df.duplicated().sum()

np.int64(0)

In [50]:
df.drop(['Unnamed: 0'] ,axis=1,inplace=True)

In [51]:
brand_dict={'TVS':1, 'Royal Enfield':2, 'Triumph':3, 'Yamaha':4, 'Honda':5, 'Hero':6,
       'Bajaj':7, 'Suzuki':8, 'Benelli':9, 'KTM':10, 'Mahindra':11, 'Kawasaki':12,
       'Ducati':13, 'Hyosung':14, 'Harley-Davidson':15, 'Jawa':16, 'BMW':17, 'Indian':18,
       'Rajdoot':19, 'LML':20, 'Yezdi':21, 'MV':22, 'Ideal':23}
char['brand']=char['brand'].map(brand_dict)

In [52]:
total_df=pd.concat((num,char),axis=1)

In [53]:
x=total_df[['age','brand','power','kms_driven','owner',]]
y=total_df['price']

In [54]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [55]:
x_train

      age  brand  power  kms_driven  owner
6302  4.0      1  180.0     12061.0      1
7037  7.0      7  220.0     40000.0      2
640   6.0      6  110.0     28329.0      1
6153  8.0      7  220.0     10000.0      2
1755  8.0      5  150.0     26000.0      1
...   ...    ...    ...         ...    ...
5191  2.0      7  100.0     15383.0      1
5226  6.0      8  150.0     45263.0      1
5390  6.0      6  100.0     45000.0      1
860   8.0      4  150.0     14836.0      1
7270  3.0      4  250.0      2126.0      1

[5844 rows x 5 columns]

In [56]:
x_test

       age  brand  power  kms_driven  owner
7062   9.0      5  250.0     35000.0      1
4553   5.0     14  250.0      9066.0      1
6505  17.0      6  100.0     48000.0      1
1918   5.0      7  150.0     20222.0      1
5227   5.0      8  150.0     27167.0      1
...    ...    ...    ...         ...    ...
2045   8.0      5  150.0     98971.0      1
527    7.0     14  250.0      2881.0      1
1783   2.0      2  350.0      6517.0      1
5065   5.0      2  350.0      5222.0      1
565    6.0      1  160.0      2980.0      1

[1462 rows x 5 columns]

In [57]:
y_train

6302     65000.0
7037     49000.0
640      32000.0
6153     36000.0
1755     70000.0
          ...
5191     38000.0
5226     62000.0
5390     30000.0
860      40000.0
7270    115800.0
Name: price, Length: 5844, dtype: float64

In [58]:
y_test

7062    125000.0
4553    220000.0
6505     16900.0
1918     58000.0
5227     58000.0
          ...
2045     25000.0
527     140000.0
1783    156000.0
5065    118000.0
565      36000.0
Name: price, Length: 1462, dtype: float64

In [59]:
# Linear Regression
model=LinearRegression()      
model.fit(x_train,y_train)

LinearRegression()

In [60]:
model.predict(x_test)

array([ 83929.37665136, 180558.39832148, -22099.35939505, ...,
       141514.63936522, 131317.32984838,  10099.13186719], shape=(1462,))

In [61]:
print("test score",model.score(x_test,y_test))
print("train score",model.score(x_train,y_train))

test score 0.7434808272417529
train score 0.7116425245703819

In [62]:
from sklearn.svm import SVC,SVR
sv=SVR()
sv.fit(x_train,y_train)

SVR()

In [63]:
print("test score:",sv.score(x_test,y_test))
print("train score:",sv.score(x_train,y_train))

test score: -0.05789256698689371
train score: -0.06164747200042009